version: '2'

services:

  james:
    depends_on:
      - elasticsearch
      - cassandra
      - tika
      - rabbitmq
      - swift
    entrypoint: bash -c "java -Dworking.directory=/root/ -jar james-server.jar"
    image: linagora/james-project:latest
    container_name: james
    hostname: james.local
    ports:
      - "80:80"
      - "25:25"
      - "110:110"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"

  elasticsearch:
    image: elasticsearch:2.4.6

  cassandra:
    image: cassandra:3.11.3
    ports:
      - "9042:9042"
  tika:
    image: logicalspark/docker-tikaserver:1.20
  rabbitmq:
    image: rabbitmq:3.7.7-management
    ports:
      - "5672:5672"
      - "15672:15672"
  swift:
    image: linagora/openstack-keystone-swift:pike
    ports:
      - "5000:5000"
      - "8080:8080"
      - "35357:35357"
