version: '3'

services:

  james:
    depends_on:
      rspamd:
          condition: service_healthy
    image: apache/james:memory-latest
    container_name: james
    hostname: james.local
    volumes:
      - $PWD/target/apache-james-rspamd-3.9.0-SNAPSHOT-jar-with-dependencies.jar:/root/extensions-jars/james-server-rspamd.jar
      - $PWD/sample-configuration/keystore:/root/conf/keystore
      - $PWD/sample-configuration/extensions.properties:/root/conf/extensions.properties
      - $PWD/sample-configuration/mailetcontainer_memory.xml:/root/conf/mailetcontainer.xml
      - $PWD/sample-configuration/listeners.xml:/root/conf/listeners.xml
      - $PWD/sample-configuration/rspamd.properties:/root/conf/rspamd.properties
      - $PWD/sample-configuration/webadmin.properties:/root/conf/webadmin.properties
      - $PWD/sample-configuration/healthcheck.properties:/root/conf/healthcheck.properties
    ports:
      - "80:80"
      - "25:25"
      - "110:110"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
      - "8000:8000"

  redis:
    image: redis:7.0.12
    command:
      - "--loglevel"
      - "debug"

  clamav:
    image: clamav/clamav:0.105

  rspamd:
    depends_on:
      clamav:
          condition: service_healthy
      redis:
          condition: service_started
    container_name: rspamd
    image: a16bitsysop/rspamd:3.3-r0-alpine3.16.2-r0
    environment:
      - REDIS=redis
      - CLAMAV=clamav
      - PASSWORD=admin
    volumes:
      - $PWD/sample-configuration/antivirus.conf:/etc/rspamd/override.d/antivirus.conf
      - $PWD/sample-configuration/statistic.conf:/etc/rspamd/statistic.conf
    ports:
      - 11334:11334