version: '3'

services:

  james:
    depends_on:
      - elasticsearch
      - cassandra
      - tika
      - rabbitmq
      - s3
      - rspamd
    image: apache/james:distributed-latest
    container_name: james
    hostname: james.local
    command:
      - --generate-keystore
    volumes:
      - $PWD/target/apache-james-rspamd-jar-with-dependencies.jar:/root/extensions-jars/james-server-rspamd.jar
      - $PWD/sample-configuration/extensions.properties:/root/conf/extensions.properties
      - $PWD/sample-configuration/mailetcontainer_distributed.xml:/root/conf/mailetcontainer.xml
      - $PWD/sample-configuration/listeners.xml:/root/conf/listeners.xml
      - $PWD/sample-configuration/rspamd.properties:/root/conf/rspamd.properties
      - $PWD/sample-configuration/webadmin.properties:/root/conf/webadmin.properties
      - $PWD/sample-configuration/healthcheck.properties:/root/conf/healthcheck.properties
    ports:
      - "80:80"
      - "25:25"
      - "110:110"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
      - "8000:8000"

  opensearch:
    image: opensearchproject/opensearch:2.1.0
    environment:
      - discovery.type=single-node

  cassandra:
    image: cassandra:3.11.10
    ports:
      - "9042:9042"

  tika:
    image: apache/tika:1.26

  rabbitmq:
    image: rabbitmq:3.8.18-management
    ports:
      - "5672:5672"
      - "15672:15672"

  s3:
    image: zenko/cloudserver:8.2.6
    container_name: s3.docker.test
    environment:
      - SCALITY_ACCESS_KEY_ID=accessKey1
      - SCALITY_SECRET_ACCESS_KEY=secretKey1
      - S3BACKEND=mem
      - LOG_LEVEL=trace
      - REMOTE_MANAGEMENT_DISABLE=1

  redis:
    image: redis:7.0.12

  clamav:
    image: clamav/clamav:0.105

  rspamd:
    depends_on:
      - redis
      - clamav
    container_name: rspamd
    image: a16bitsysop/rspamd:3.3-r0-alpine3.16.2-r0
    environment:
      - REDIS=redis
      - CLAMAV=clamav
      - PASSWORD=admin
    volumes:
      - $PWD/sample-configuration/antivirus.conf:/etc/rspamd/override.d/antivirus.conf
      - $PWD/sample-configuration/statistic.conf:/etc/rspamd/statistic.conf
    ports:
      - 11334:11334