version: '3'

services:

  james:
    depends_on:
      - opensearch
      - cassandra
      - tika
    image: apache/james:cassandra-latest
    container_name: james
    hostname: james.local
    ports:
      - "80:80"
      - "25:25"
      - "110:110"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
      - "8000:8000"

  opensearch:
    image: opensearchproject/opensearch:2.1.0
    environment:
      - discovery.type=single-node
      - DISABLE_INSTALL_DEMO_CONFIG=true
      - DISABLE_SECURITY_PLUGIN=true

  cassandra:
    image: cassandra:3.11.10
    ports:
      - "9042:9042"

  tika:
    image: apache/tika:2.8.0.0

